import { Link, useParams } from 'react-router-dom';
import { Save } from 'lucide-react';
import PageHeader from '../../components/workspace/PageHeader';
import FormCard from '../../components/workspace/FormCard';
import { privileges, roles } from '../../data/workspace';

export default function RoleFormPage() {
    const { id } = useParams(); const role = roles.find((item)=>String(item.id)===id); const editing=Boolean(id); const moderatorDefaults=['pages.view','pages.create','pages.update'];
    return <div className="space-y-6"><PageHeader eyebrow="Access control" title={editing?`Edit ${role?.name ?? 'role'}`:'Add role'} description="Define a role and select exactly which privileges it grants." actions={<><Link to="/admin/roles" className="inline-flex h-10 items-center rounded-lg border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-700">Cancel</Link><button className="inline-flex h-10 items-center gap-2 rounded-lg bg-teal-700 px-4 text-sm font-semibold text-white"><Save className="h-4 w-4" />Save role</button></>} /><FormCard title="Role details" description="Use role names for organization, not hard-coded permission checks." aside="The backend will authorize actions by privileges. Changing a role's privilege set should immediately change what its users can do."><label className="block text-sm font-semibold text-slate-700">Role name<input defaultValue={role?.name} className="mt-2 w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm outline-none focus:border-teal-500" placeholder="Role name" /></label><label className="mt-5 block text-sm font-semibold text-slate-700">Description<textarea defaultValue={role?.description} rows="3" className="mt-2 w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm font-normal outline-none focus:border-teal-500" /></label></FormCard><FormCard title="Privileges" description="Select the capabilities available to this role." aside={`${privileges.length} privileges are currently defined in this design.`}><div className="grid gap-3 sm:grid-cols-2">{privileges.map((privilege)=><label key={privilege.id} className="flex cursor-pointer gap-3 rounded-xl border border-slate-200 p-4 hover:border-teal-300 hover:bg-teal-50/30"><input type="checkbox" defaultChecked={role?.name==='Admin' || (role?.name==='Moderator' && moderatorDefaults.includes(privilege.name))} className="mt-1 h-4 w-4 rounded border-slate-300 accent-teal-700" /><span><span className="block font-mono text-xs font-semibold text-slate-800">{privilege.name}</span><span className="mt-1 block text-xs leading-5 text-slate-500">{privilege.description}</span></span></label>)}</div></FormCard></div>;
}
