import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Save } from 'lucide-react';
import api, { apiErrorMessage } from '../../api/client';
import PageHeader from '../../components/workspace/PageHeader';
import FormCard from '../../components/workspace/FormCard';

export default function RoleFormPage() {
    const { id } = useParams(); const editing = Boolean(id); const navigate = useNavigate();
    const [privileges, setPrivileges] = useState([]); const [form, setForm] = useState({ name: '', description: '', privilege_ids: [] }); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
    useEffect(() => { Promise.all([api.get('/privileges'), editing ? api.get(`/roles/${id}`) : Promise.resolve(null)]).then(([privilegesResponse, roleResponse]) => { setPrivileges(privilegesResponse.data.data); if (roleResponse) { const role = roleResponse.data.data; setForm({ name: role.name, description: role.description || '', privilege_ids: (role.privileges || []).map((p) => p.id) }); } }).catch((e) => setError(apiErrorMessage(e))); }, [id]);
    function toggle(pid) { setForm((f) => ({ ...f, privilege_ids: f.privilege_ids.includes(pid) ? f.privilege_ids.filter((id) => id !== pid) : [...f.privilege_ids, pid] })); }
    async function submit(e) { e.preventDefault(); setSubmitting(true); setError(''); try { editing ? await api.patch(`/roles/${id}`, form) : await api.post('/roles', form); navigate('/admin/roles'); } catch (err) { setError(apiErrorMessage(err, 'Unable to save role.')); } finally { setSubmitting(false); } }
    return <form onSubmit={submit} className="space-y-6"><PageHeader eyebrow="Access control" title={editing ? 'Edit role' : 'Add role'} description="Define a role and select exactly which privileges it grants." actions={<><Link to="/admin/roles" className="inline-flex h-10 items-center rounded-lg border border-slate-200 bg-white px-4 text-sm font-semibold">Cancel</Link><button disabled={submitting} className="inline-flex h-10 items-center gap-2 rounded-lg bg-teal-700 px-4 text-sm font-semibold text-white"><Save className="h-4 w-4" />Save role</button></>} />{error ? <div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</div> : null}<FormCard title="Role details" description="Role names organize access; privileges authorize actions." aside="Changing privileges immediately changes what assigned users can do."><label className="block text-sm font-semibold text-slate-700">Role name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm outline-none focus:border-teal-500" /></label><label className="mt-5 block text-sm font-semibold text-slate-700">Description<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} rows="3" className="mt-2 w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm font-normal outline-none focus:border-teal-500" /></label></FormCard><FormCard title="Privileges" description="Select capabilities available to this role." aside={`${privileges.length} privileges are defined.`}><div className="grid gap-3 sm:grid-cols-2">{privileges.map((privilege) => <label key={privilege.id} className="flex cursor-pointer gap-3 rounded-xl border border-slate-200 p-4 hover:border-teal-300"><input type="checkbox" checked={form.privilege_ids.includes(privilege.id)} onChange={() => toggle(privilege.id)} className="mt-1 h-4 w-4 accent-teal-700" /><span><span className="block font-mono text-xs font-semibold">{privilege.name}</span><span className="mt-1 block text-xs leading-5 text-slate-500">{privilege.description}</span></span></label>)}</div></FormCard></form>;
}
